### ISSUE TITLE
Autopatcher script has possibility of not recognizing xdelta/homebrew path

### ISSUE THREAD

**Issue by Shock9616** [Miepee/AM2R-Autopatcher-Mac#1]
When I installed AM2R with this patcher last night, I tried double clicking the `patcher.command` file to run the script. The problem is that I got a message saying `xdelta could not be found in PATH. Do you want to automatically install Homebrew and xdelta? Declining this will make you have to install xdelta on your own.` even though I made sure to install xdelta before running the script. When I tried installing xdelta with the script, it also prompted me to install Homebrew which I also have on my system. I tried installing Homebrew with the script as well, but it just downloaded the files, then spit out a bunch of text and closed the window before I could see what it said.

The way that I got around this was to use the terminal to `cd` into the autopatcher's folder and run the script with `./autopatcher.command` and then it worked perfectly with my pre-installed version of xdelta. Not being very well versed in bash scripting, I don't know exactly what's going on here, but my guess would be that when the script is run from finder, it doesn't get access to the various programs I have installed. I'm not sure if this is something that can be fixed, but until it is I would suggest adding this as a troubleshooting step or something to help people who aren't as tech-savvy so that they can still play the game.

**Comment by Miepee** [comment]
> but my guess would be that when the script is run from finder, it doesn't get access to the various programs I have installed.

Nope, I tested this already. The way I'm checking if a program is installed or not is by checking if it is in PATH. And that doesn't change if you run it from Finder or not. Did check this just to be sure during bug-testing and can't replicate it now.
Would need to get the "bunch of text" that appeared for me to have any chance in what's going on.  
Did you try if doing `open autopatcher.command` also errors or does that work fine? If that errors you can generate a log with `open autopatcher.command --stdout log.txt --stderr log.txt` (I think those two were the right arguments. Not on MacOS right now, will edit or post the correction whenever I do.)

**Comment by Shock9616** [comment]
I tried the command but that didn't generate any log files. Instead I took a screen recording and then went through frame by frame so that I could see the text and copied it out.

```
-------------------------------------------

AM2R 1.5.5 Shell Autopatching Utility
Scripted by Miepee

-------------------------------------------
xdelta could not be found in PATH. Do you want to automatically install Homebrew and xdelta? Declining this will make you have to install xdelta on your own.
(Y/N)
y
Homebrew could not be found. Installing homebrew....
==> Checking for `sudo` access (which may request your password)...
Password:
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort:
==> /usr/bin/sudo /usr/sbin/chown -R myusername:admin /usr/local/Homebrew
==> Downloading and installing Homebrew...
HEAD is now at 3373a82d2 Merge pull request #12545 from Homebrew/dependabot/bundler/Library/Homebrew/sorbet-0.5.9445
Warning: /usr/local/bin is not in your PATh
  Instructions on hwo to configure your shell for Homebrew
  can be found in the 'Next steps' section below.
==> Installation successful!

==> Homebrew has enabled anonymous aggregate formulae and cask analytics.
Read the analytics documentation (and how to opt-out) here:
  http://docs.brew.sh/Analytics
No analytics data has been sent yet (nor will any be during this install run).

==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations

==> Next steps:
- Run brew help to get started
- Further documentation:
    https://docs.brew.sh
```
It seems like it's successfully "installing" Homebrew (it still doesn't work if I run it again) and then closing the window. I still don't know why this is happening, but now we know what the "bunch of text" is 🤷‍♂️

**Comment by Miepee** [comment]
Can you list the model number of your mac?

**Comment by Shock9616** [comment]
A1708. It's a 2017 13" MacBook Pro with a 2.3 GHz I5-7360U

**Comment by Miepee** [comment]
Could you also give me the output of `bash --version`, `zsh --version`  and current OS version please?

**Comment by Shock9616** [comment]
```
~ ❯ bash --version && zsh --version    
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)
Copyright (C) 2007 Free Software Foundation, Inc.
zsh 5.8 (x86_64-apple-darwin21.0)

~ ❯ 
```

zsh is my login shell

**Comment by Shock9616** [comment]
Turns out the problem was the terminal I was using. I have scripts like this configured to open in the Kitty terminal, not the default MacOS terminal. For whatever reason kitty looks at a different $PATH variable than the default one which was messing with the patcher script. When I tried opening the script in the default terminal it worked perfectly.

**Comment by Miepee** [comment]
That said, there's still a potential issue where the autopatcher might not recognize xdelta/homebrew because homebrew doesn't guarantuee adding its installation path to PATH.
