### ISSUE TITLE
iOS Patch

### ISSUE THREAD

**Issue by illando** [Miepee/AM2R-Autopatcher-Mac#3]
Hi Miepee. Thanks a lot for this patch!
Do you think it would be possible to enable this patch to create also an iOS version?
Just the IPA... then it would be optional to choose how to sign it and install on the device.

Thanks.

**Comment by Miepee** [comment]
Already tried, won't be happening.
There are too many hurdles with it, the biggest of them is that neither I, nor anyone I know has a legit iOS module.
