### ISSUE TITLE
Mods compatible with this autopatcher

### ISSUE THREAD

**Issue by Shock9616** [Miepee/AM2R-Autopatcher-Mac#4]
Hey I'm just wondering if there is a list of mac compatible mods anywhere or if there even are mac compatible mods. I'm also wondering what needs to be different from other versions of mods. Would it be fairly easy for me to modify a windows/linux mod (ex. Multitroid) to make it compatible here or would I have to ask the devs of the mods have to create a whole new version specifically for this?

**Comment by Miepee** [comment]
Non-exhaustive list of mods can be found here, this includes Mac compatible ones:
https://gitlab.com/Miepee/AM2R-Mods

It is possible to modify **VM** Windows Builds into Mac Builds [AM2RPortHelper](https://github.com/Miepee/AM2RPortHelper) (Note that this requires either installing the Mod on Windows before feeding it into the program, or patching/installing it manually on other OS). Keep the Mac Notes on that page in mind.   
After a Mac Build has been created, it is possible to use this [AM2RModPacker fork](https://github.com/Miepee/AM2RModPacker-Mac) (Windows only for now, works via WINE and Mono on Linux, not sure about Mac) to create DMCA-safe Mods.

Modifying YYC Builds is impossible, for that you'd have to ask the Mod devs to release a special build.

---

I know that by default one has to remove two or three snippets of code from the Community Source before feeding it into the PortHelper, but don't know which places it were by heart. Procedure is somewhat like this:
- open data.win in UndertaleModTool
- search for instances of `immersion_play_effect` and `immersion_stop` via scripts -> builtin -> search and either remove them or make them Android exclusive. See this PR for an example: https://github.com/AM2R-Community-Developers/AM2R-Community-Updates/pull/109/files
- search for instances of `font_replace` and delete or lock the whole if chunk behind an OS check. Don't have an example for this one.

**Comment by Shock9616** [comment]
Awesome! Thanks! I'm just wondering, the AM2RPortHelper script seems to only support porting to Linux or Android, is there a flag or something that I need to give it to port to mac? I don't see anything about this in the README...

**Comment by Miepee** [comment]
Slightly out-of-scope for this issue, but i'll answer it here for now.
The current release (1.2) does not support Mac, but the in-dev does. Either wait until a new release comes out, or build from source. [Artifacts also exist](https://github.com/Miepee/AM2RPortHelper/actions), in case you can't build from source.
